# Generated by Django 2.2.8 on 2020-04-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/Post/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Video',
            field=models.FileField(blank=True, null=True, upload_to='media/video/'),
        ),
    ]
