# Generated by Django 2.2.8 on 2020-04-22 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20200421_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reply_set', to='Post.Comment'),
        ),
    ]
