# Generated by Django 2.2.8 on 2020-04-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_auto_20200422_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Archived',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
