# Generated by Django 2.2.8 on 2020-04-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_post_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Archived',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
