# Generated by Django 2.2.8 on 2020-04-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20200408_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Private',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
