# Generated by Django 2.2.8 on 2020-04-19 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_auto_20200409_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TextField', models.TextField()),
                ('ImageField', models.ImageField(null=True, upload_to='media/status/Image')),
                ('VideoFields', models.FileField(null=True, upload_to='media/status/video')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
            ],
        ),
    ]
