# Generated by Django 2.2.8 on 2020-04-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='ImageField',
            field=models.ImageField(blank=True, null=True, upload_to='media/status/Image'),
        ),
        migrations.AlterField(
            model_name='status',
            name='TextField',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='VideoFields',
            field=models.FileField(blank=True, null=True, upload_to='media/status/video'),
        ),
    ]
