# Generated by Django 2.2.8 on 2020-04-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_auto_20200419_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='Descreption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
