# Generated by Django 2.2.8 on 2020-04-21 06:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_status_descreption'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 4, 21, 6, 47, 4, 504816, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
