# Generated by Django 2.2.8 on 2020-04-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_status_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='Archived',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
