# Generated by Django 2.2.8 on 2020-04-10 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmed',
            old_name='rejected',
            new_name='Timestamp',
        ),
        migrations.RemoveField(
            model_name='confirmed',
            name='created',
        ),
        migrations.RemoveField(
            model_name='confirmed',
            name='viewed',
        ),
        migrations.RemoveField(
            model_name='request',
            name='Timestamp',
        ),
        migrations.AddField(
            model_name='request',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='request',
            name='rejected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='viewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
