# Generated by Django 2.2.8 on 2020-04-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0002_auto_20200410_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='rejected',
        ),
    ]
